# Generated by Django 4.2.6 on 2023-10-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0005_product_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='auther',
            new_name='owner',
        ),
    ]
